name: Makefile CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: make

  build-linux-i386:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: gcc-multilib
        version: 1.0
    - name: Compile
      run: make ARCH=-m32
    - name: Compress (gzip)
      run: gzip -9v build/bin-i386/studiomdl
    
    - name: version
      run: echo "::set-output name=version::master-$(git rev-parse --short HEAD)"
      id: version
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ steps.version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/bin-i386/studiomdl.gz
        asset_name: studiomdl-ubuntu-latest-i386.gz
        asset_content_type: application/gzip
