name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: make

  build-linux-i386:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: GCC Multilib
      run: export DEBIAN_FRONTEND=noninteractive && apt update && apt install -y gcc-multilib
    - name: Compile
      run: make ARCH=-m32
